server:
  port : 7003
spring :
 security :
  user :
   name : root
   password : 123456
 application :
  name : eurekaserver
eureka:
  instance :
    hostname : eureka03
  client:
    serviceUrl:
      defaultZone : http://root:123456@eureka01:7001/eureka/,http://root:123456@eureka02:7002/eureka/




