server:
  port : 7072
  name : serviceprovider01
spring :
  application :
    name : serviceprovider #应用名称，集群下应该相同
  datasource :
    username : root
    password : zsxm123456.
    url : jdbc:mysql://127.0.0.1:3306/sshe?useUnicode=true&characterEncoding=utf-8
    driver-class-name : com.mysql.cj.jdbc.Driver
    type : com.alibaba.druid.pool.DruidDataSource
    druid:
     initialSize: 5
     minIdle: 5
     maxActive: 20
     maxWait: 60000
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: SELECT 1 FROM DUAL
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     filters: stat,wall,log4j2                               # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
     maxPoolPreparedStatementPerConnectionSize: 20                               #'wall'用于防火墙，SpringBoot中没有log4j，我改成了log4j2
     useGlobalDataSourceStat: true
     connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500                              #最大PSCache连接
     web-stat-filter:
      enabled: true
      url-pattern: "/*"
      exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
     stat-view-servlet:
      url-pattern: "/druid/*"
      allow: 127.0.0.1
      login-username: root
      login-password: zsxm123456.
      deny: 192.168.1.254
      reset-enable: true
      enabled: true
                                    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录

                                    # 配置StatFilter

                                      #默认为false，设置为true启动


mybatis-plus:
  # model的包
  mapper-locations : classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: false #开启驼峰uName自动映射到u_name
eureka:
  instance :
    hostname : eureka03
    id : serviceprovider01
  client:
    serviceUrl:
      defaultZone : http://root:123456@eureka01:7001/eureka/,http://root:123456@eureka02:7002/eureka/,http://root:123456@eureka03:7003/eureka/
management :
 endpoints :
  web :
   exposure :
    include : shutdown
 endpoint :
  shutdown :
   enable : true


